name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: bljghubhkofddfrezkhn

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1.2.0
        with:
          version: 1.0.0

      - run: supabase functions deploy --project-ref $PROJECT_ID --no-verify-jwt
